// src/lib/nocodb.config.ts
type NocoDbEnv = {
  baseUrl: string;
  apiToken: string;
  projectId: string;
};

function reqEnv(name: string) {
  const v = (import.meta as any).env?.[name];
  if (!v) throw new Error(`[NocoDB] ENV ausente: ${name}`);
  return String(v);
}

export const nocodbEnv: NocoDbEnv = {
  baseUrl: reqEnv("VITE_NOCODB_BASE_URL").replace(/\/+$/, ""),
  apiToken: reqEnv("VITE_NOCODB_API_TOKEN"),
  projectId: reqEnv("VITE_NOCODB_PROJECT_ID"),
};

// =====================
// TABLE IDS
// =====================
export const nocodbTables = {
  SETORES: reqEnv("VITE_NOCODB_TABLE_SETORES"),
  EMPRESAS_FORNECEDORES: reqEnv("VITE_NOCODB_TABLE_EMPRESAS_FORNECEDORES"),
  CATEGORIAS: reqEnv("VITE_NOCODB_TABLE_CATEGORIAS"),
  CONTAS: reqEnv("VITE_NOCODB_TABLE_CONTAS"),
  CONTAS_PROTOCOLADAS: reqEnv("VITE_NOCODB_TABLE_CONTAS_PROTOCOLADAS"),
  RECORRENCIA: reqEnv("VITE_NOCODB_TABLE_RECORRENCIA"),
  GERACOES_RECORRENCIA: reqEnv("VITE_NOCODB_TABLE_GERACOES_RECORRENCIA"),
};

// =====================
// LINK IDS (TRADUZIDOS)
// Aqui a gente expõe nomes "bonitos" pro app,
// mas por baixo lê exatamente os nomes do seu .env
// =====================
export const nocodbLinks = {
  // SETORES -> (Empresas / Categorias)
  SETOR_EMPRESAS: reqEnv("VITE_NOCODB_LINK_SETORES_EMPRESAS_FORNECEDORES"),
  SETOR_CATEGORIAS: reqEnv("VITE_NOCODB_LINK_SETORES_CATEGORIAS"),
  SETOR_CONTAS: reqEnv("VITE_NOCODB_LINK_SETORES_CONTAS"),
  SETOR_CONTAS_PROTOCOLADAS: reqEnv("VITE_NOCODB_LINK_SETORES_CONTAS_PROTOCOLADAS"),

  // CONTAS -> (Empresa / Categoria / Setor / Gerações)
  CONTA_EMPRESA: reqEnv("VITE_NOCODB_LINK_CONTA_EMPRESA"),
  CONTA_CATEGORIA: reqEnv("VITE_NOCODB_LINK_CONTA_CATEGORIA"),
  CONTA_SETOR: reqEnv("VITE_NOCODB_LINK_CONTA_SETOR"),
  CONTA_CONTAS_PROTOCOLADAS: reqEnv("VITE_NOCODB_LINK_CONTA_CONTAS_PROTOCOLADAS"),
  CONTA_RECORRENCIA: reqEnv("VITE_NOCODB_LINK_CONTA_RECORRENCIA"),
  CONTA_GERACOES_RECORRENCIA: reqEnv("VITE_NOCODB_LINK_CONTA_GERACOES_RECORRENCIA"),

  // (opcional, caso use depois)
  EMPRESA_SETOR: reqEnv("VITE_NOCODB_LINK_EMPRESA_SETOR"),
  EMPRESA_CONTAS: reqEnv("VITE_NOCODB_LINK_EMPRESA_CONTAS"),
  EMPRESA_CONTAS_PROTOCOLADAS: reqEnv("VITE_NOCODB_LINK_EMPRESA_CONTAS_PROTOCOLADAS"),
  EMPRESA_RECORRENCIA: reqEnv("VITE_NOCODB_LINK_EMPRESA_RECORRENCIA"),

  CATEGORIA_SETORES: reqEnv("VITE_NOCODB_LINK_CATEGORIA_SETORES"),
  CATEGORIA_CONTAS: reqEnv("VITE_NOCODB_LINK_CATEGORIA_CONTAS"),
  CATEGORIA_RECORRENCIA: reqEnv("VITE_NOCODB_LINK_CATEGORIA_RECORRENCIA"),

  RECORRENCIA_EMPRESA: reqEnv("VITE_NOCODB_LINK_RECORRENCIA_EMPRESA"),
  RECORRENCIA_CONTA: reqEnv("VITE_NOCODB_LINK_RECORRENCIA_CONTA"),
  RECORRENCIA_CATEGORIA: reqEnv("VITE_NOCODB_LINK_RECORRENCIA_CATEGORIA"),
  RECORRENCIA_GERACOES: reqEnv("VITE_NOCODB_LINK_RECORRENCIA_GERACOES"),

  GERACAO_CONTA: reqEnv("VITE_NOCODB_LINK_GERACAO_CONTA"),
  GERACAO_RECORRENCIA: reqEnv("VITE_NOCODB_LINK_GERACAO_RECORRENCIA"),

  CONTA_PROTOCOL_EMPRESA: reqEnv("VITE_NOCODB_LINK_CONTA_PROTOCOL_EMPRESA"),
  CONTA_PROTOCOL_CONTA: reqEnv("VITE_NOCODB_LINK_CONTA_PROTOCOL_CONTA"),
  CONTA_PROTOCOL_SETOR: reqEnv("VITE_NOCODB_LINK_CONTA_PROTOCOL_SETOR"),
};
